services:
  - type: web
    name: afirmatii-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    disk:
      name: afirmatii-data
      mountPath: /opt/render/project/src
      sizeGB: 1
